routes/web.php
<?php

Route::view("/{path?}", "layouts.index")->where('path', '.*');

app/UserPaymentConfig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class UserPaymentConfig extends Model
{
    /** 
     * This models immutable values.
     *
     * @var array 
     */
    protected $guarded = [];

    /**
     * Attributes to automatically append onto the response.
     * 
     * @var array
     */
    protected $appends = [
        'hidden_card_number', 'expiry_date', 'formatted_phone_number', 'formatted_mobile_number'
    ];

    /**
     * This model relationship belongs to \App\User.
     * 
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * This model relationship belongs to \App\OrderHistory.
     * 
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function orderHistory()
    {
        return $this->hasOne('App\OrderHistory');
    }

    /**
     * Set a publicily accessible identifier to get the hidden cart number for this unique instance.
     * 
     * @return  string
     */
    public function getHiddenCardNumberAttribute()
    {
        $cardNumber = $this->attributes['card_number'];
        $length = strlen($cardNumber);

        $cardNumber = substr($cardNumber, -4, strlen($cardNumber));
        $cardNumber = str_pad($cardNumber, 16, "*", STR_PAD_LEFT);

        return $cardNumber;
    }

    /**
     * Set a publicily accessible identifier to get the expiry date for this unique instance.
     * 
     * @return  \Carbon\Carbon
     */
    public function getExpiryDateAttribute()
    {
        return Carbon::createFromDate($this->attributes['expiry_year'], $this->attributes['expiry_month'], 1)->format('m/Y');
    }

    /**
     * Set a publicily accessible identifier to get the edit expiry date for this unique instance.
     * 
     * @return  \Carbon\Carbon
     */
    public function getEditExpiryDateAttribute()
    {
        return Carbon::createFromDate($this->attributes['expiry_year'], $this->attributes['expiry_month'], 1)->format('Y-m');
    }

    /**
     * Set a publicily accessible identifier to get the edit expiry date for this unique instance.
     * 
     * @return  \Carbon\Carbon
     */
    public function getFormattedPhoneNumberAttribute()
    {
        return $this->attributes['phone_number_extension'] . ' ' . $this->attributes['phone_number'];
    }

    /**
     * Set a publicily accessible identifier to get the formatted mobile number for this unique instance.
     * 
     * @return  string
     */
    public function getFormattedMobileNumberAttribute()
    {
        return $this->attributes['mobile_number_extension'] . ' ' . $this->attributes['mobile_number'];
    }
}

app/Http/Controllers/UserPaymentConfigController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\CommonHelper;
use Illuminate\Http\Request;
use App\UserPaymentConfig;
use Validator;

class UserPaymentConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \App\User::attemptAuth();

        $billingCards = UserPaymentConfig::where('user_id', $user->id)->paginate(10);

        $message = "Successful";
        return response()->json(compact('billingCards', 'message'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserPaymentConfig $userPaymentConfig, Request $request)
    {
        $user = \App\User::attemptAuth();

        $validator = Validator::make($request->all(), [
            'card_holder_name' => 'required|min: 6|max: 191',
            'card_number' => 'required|digits: 16',
            'expiry_date' => 'required', // format 2018-01

            'building_name' => 'required|string|max:191',
            'street_address1' => 'required|max:191',
            'street_address2' => 'max:191',
            'street_address3' => 'max:191',
            'street_address4' => 'max:191',
            'postcode' => 'required|string|min: 5|max:191',
            'city' => 'required|string|min: 4|max:191',
            'country' => 'required|string|min: 4|max:191',
            'phone_number_extension' => 'required|min: 2|max:191',
            'phone_number' => 'required|min: 5|max:191',
            'mobile_number_extension' => 'max:191',
            'mobile_number' => 'max:191',
        ]);

        if(empty($validator->errors()->all()))
        {
            $expiry_date = explode('-', $request->input('expiry_date'));
            $expiry_year = $expiry_date[0];
            $expiry_month = $expiry_date[1];

            if(strtotime(date("$expiry_year-$expiry_month")) >= strtotime(date('Y-m')))
            {
                if(in_array(request('country'), CommonHelper::getCountriesList()))
                {
                    $data = array(
                        'user_id' => $user->id,

                        'card_holder_name' => request('card_holder_name'),
                        'card_number' => request('card_number'),
                        'expiry_month' => $expiry_month,
                        'expiry_year' => $expiry_year,

                        'building_name' => request('building_name'),
                        'street_address1' => request('street_address1'),
                        'street_address2' => request('street_address2'),
                        'street_address3' => request('street_address3'),
                        'street_address4' => request('street_address4'),
                        'postcode' => request('postcode'),
                        'city' => request('city'),
                        'country' => request('country'),
                        'county' => request('county'), // nullable
                        'phone_number_extension' => request('phone_number_extension'),
                        'phone_number' => request('phone_number'),
                        'mobile_number_extension' => request('mobile_number_extension'), // nullable
                        'mobile_number' => request('mobile_number'), // nullable
                    );

                    UserPaymentConfig::create($data);

                    return response()->json([
                        "errors" => ['Billing card successfully created.'],
                        "message" => "Successful"
                    ], config("app.http.created"));
                }
                else
                {
                    return response()->json([
                        'errors' => ['Invalid country provided'],
                        "message" => "Unsuccessful"
                    ], config("app.http.bad_request"));
                }
            }
            else
            {
                return response()->json([
                    'errors' => ['Invalid expiry date provided.'],
                    "message" => "Unsuccessful"
                ], config("app.http.bad_request"));
            }
        }
        else
        {
            return response()->json([
                'errors' => $validator->errors()->all(),
                "message" => "Unsuccessful"
            ], config("app.http.bad_request"));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\UserPaymentConfig  $userPaymentConfig
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UserPaymentConfig $userPaymentConfig)
    {
        $user = \App\User::attemptAuth();
        if($userPaymentConfig['user_id'] === $user->id)
        {
            $validator = Validator::make($request->all(), [
                'card_holder_name' => 'required|min: 6|max: 191',
                'card_number' => 'required|digits: 16',
                'expiry_date' => 'required', // format 2018-01

                'building_name' => 'required|string|max:191',
                'street_address1' => 'required|max:191',
                'street_address2' => 'max:191',
                'street_address3' => 'max:191',
                'street_address4' => 'max:191',
                'postcode' => 'required|string|min: 5|max:191',
                'city' => 'required|string|min: 4|max:191',
                'country' => 'required|string|min: 4|max:191',
                'phone_number_extension' => 'required|min: 2|max:191',
                'phone_number' => 'required|min: 5|max:191',
                'mobile_number_extension' => 'max:191',
                'mobile_number' => 'max:191',
            ]);

            if(empty($validator->errors()->all()))
            {
                $expiry_date = explode('-', $request->input('expiry_date'));
                $expiry_year = $expiry_date[0];
                $expiry_month = $expiry_date[1];

                if(strtotime(date("$expiry_year-$expiry_month")) >= strtotime(date('Y-m')))
                {
                    if(in_array(request('country'), CommonHelper::getCountriesList()))
                    {
                        $data = array(
                            'card_holder_name' => request('card_holder_name'),
                            'card_number' => request('card_number'),
                            'expiry_month' => $expiry_month,
                            'expiry_year' => $expiry_year,

                            'building_name' => request('building_name'),
                            'street_address1' => request('street_address1'),
                            'street_address2' => request('street_address2'),
                            'street_address3' => request('street_address3'),
                            'street_address4' => request('street_address4'),
                            'postcode' => request('postcode'),
                            'city' => request('city'),
                            'country' => request('country'),
                            'county' => request('county'), // nullable
                            'phone_number_extension' => request('phone_number_extension'),
                            'phone_number' => request('phone_number'),
                            'mobile_number_extension' => request('mobile_number_extension'), // nullable
                            'mobile_number' => request('mobile_number'), // nullable
                        );

                        UserPaymentConfig::where('id', $userPaymentConfig->id)->update($data);

                        return response()->json([
                            "errors" => ['Billing card successfully updated.'],
                            "message" => "Successful"
                        ]);
                    }
                    else
                    {
                        return response()->json([
                            'errors' => ['Invalid country provided'],
                            "message" => "Uncuccessful"
                        ], config("app.http.bad_request"));
                    }
                }
                else
                {
                    return response()->json([
                        'errors' => ['Invalid expiry date provided.'],
                        "message" => "Uncuccessful"
                    ], config("app.http.bad_request"));
                }
            }
            else
            {
                return response()->json([
                    'errors' => $validator->errors()->all(),
                    "message" => "Uncuccessful"
                ], config("app.http.bad_request"));
            }
        }
        else
        {
            return response()->json([
                "message" => "Unauthorized"
            ], config("app.http.unauthorized"));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\UserPaymentConfig  $userPaymentConfig
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserPaymentConfig $userPaymentConfig, Request $request)
    {
        $user = \App\User::attemptAuth();
        if($userPaymentConfig['user_id'] === $user->id)
        {
            $validator = Validator::make($request->all(), [
                'choice' => 'required|boolean',
            ]);

            $user = auth()->user();

            if(empty($validator->errors()->all()))
            {
                $choice = (bool) $request->input('choice');

                if($choice !== FALSE)
                {
                    UserPaymentConfig::destroy($userPaymentConfig->id);

                    return response()->json([
                        "message" => "Successful",
                    ]);
                }

resources/views/user_payment_config/delete.blade.php
@extends('layouts.master')

@section('content')

<style>
    div.col-md-4 {
        margin-bottom:20px;
    }
</style>
<div class="row">
    <div class="col-md-12">

        <div class="card">

            <div class="card-body">
                <div class="lead">
                    Delete Your Billing Card
                </div>

                <br/>

                <div class="card-text">
                    @include('layouts.errors')
                    <div class="row">

                        <div class="col-md-4 offset-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-text">
                                        <p class='text-center'><strong>Billing</strong></p>

                                        <p>{{ $billingCard->card_holder_name }}</p>
                                        <p>{{ $billingCard->card_number }}</p>
                                        <p>{{ $billingCard->expiry_date }}</p>

                                        <p class='text-center'><strong>Address</strong></p>
                                        <p>{{ $billingCard->building_name }}</p>
                                        <p>{{ $billingCard->street_address1 }}</p>
                                        <p>{{ $billingCard->street_address2 }}</p>
                                        <p>{{ $billingCard->street_address3 }}</p>
                                        <p>{{ $billingCard->street_address4 }}</p>
                                        <p>{{ $billingCard->county }}</p>
                                        <p>{{ $billingCard->city }}</p>
                                        <p>{{ $billingCard->postcode }}</p>
                                        <p>{{ $billingCard->country }}</p>
                                        <p>{{ $billingCard->formatted_phone_number }}</p>
                                        <p>{{ $billingCard->formatted_mobile_number }}</p>

                                    </div>
                                </div>
                                <div class="card-footer text-center">
                                    <form class='form' action="{{ route('billingDestroy', $billingCard->id) }}" method='POST'>
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <div class="form-group">
                                            <label>Are you sure you want to delete this card?
                                                <select name="choice" class='form-control'>
                                                    <option value="0">No</option>
                                                    <option value="1">Yes</option>
                                                </select>
                                            </label>
                                        </div>

                                        <div class="form-group">
                                            <input type="submit" class='form-control btn btn-primary'>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="float-left">
                        <button class='btn btn-default' onclick='history.go(-1);'>Back</button>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

@stop

resources/views/user_payment_config/edit.blade.php
@extends('layouts.master')

@section('content')

<style>
    div.col-md-4 {
        margin-bottom:20px;
    }
    div.custom-div {
        border-left:1px solid lightgrey;
        border-right:1px solid lightgrey;
    }
</style>
<div class="row">
    <div class="col-md-12">

        <div class="card">

            <div class="card-body">
                <div class="lead">
                    Edit Your Billing Card
                </div>

                <br/>

                <div class="card-text">
                    <div class="row">
                        <div class="col-md-12">
                            @include('layouts.errors')
                            <form class='form' action="{{ route('billingUpdate', $billingCard->id) }}" method='POST'>
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <div class="card">
                                    <div class="card-body">
                                        <div class="card-text">
                                            <div class="row">
                                                <div class="col-md-4">

                                                    <p class='text-center'><strong>Billing</strong></p>

                                                    <div class="form-group">
                                                        <label>Card Holder Name*:
                                                            <input class='form-control' name='card_holder_name' value='{{ $billingCard->card_holder_name }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Card Number*:
                                                            <input class='form-control' name='card_number' value='{{ $billingCard->card_number }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Expiry Date*:
                                                            <input class='form-control' type='month' name='expiry_date' value='{{ $billingCard->edit_expiry_date }}'>
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 custom-div">
                                                    <p class='text-center'><strong>Address</strong></p>

                                                    <div class="form-group">
                                                        <label>Building Name / Number*:
                                                            <input class='form-control' name='building_name' value='{{ $billingCard->building_name }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Street Address 1*:
                                                            <input class='form-control' name='street_address1' value='{{ $billingCard->street_address1 }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Street Address 2:
                                                            <input class='form-control' name='street_address2' value='{{ $billingCard->street_address2 }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Street Address 3:
                                                            <input class='form-control' name='street_address3' value='{{ $billingCard->street_address3 }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Street Address 4:
                                                            <input class='form-control' name='street_address4' value='{{ $billingCard->street_address4 }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>County:
                                                            <input class='form-control' name='county' value='{{ $billingCard->county }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>City*:
                                                            <input class='form-control' name='city' value='{{ $billingCard->city }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Postcode*:
                                                            <input class='form-control' name='postcode' value='{{ $billingCard->postcode }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Country*:
                                                            <select name="country" class='form-control'>
                                                                @foreach(App\Helpers\CommonHelper::getCountriesList() as $shortName => $longName)
                                                                    @if($billingCard->country === $longName)
                                                                        <option selected value="{{ $longName }}">{{ $longName }}</option>
                                                                    @else
                                                                        <option value="{{ $longName }}">{{ $longName }}</option>
                                                                    @endif
                                                                @endforeach
                                                            </select>
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <p class='text-center'><strong>Contact Numbers</strong></p>

                                                    <div class="form-group">
                                                        <label>Phone Number Extension*:
                                                            <input class='form-control' name='phone_number_extension' value='{{ $billingCard->phone_number_extension }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Phone Number*:
                                                            <input class='form-control' name='phone_number' value='{{ $billingCard->phone_number }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Mobile Number Extension:
                                                            <input class='form-control' name='mobile_number_extension' value='{{ $billingCard->mobile_number_extension }}'>
                                                        </label>
                                                    </div>

                                                    <div class="form-group">
                                                        <label>Mobile Number:
                                                            <input class='form-control' name='mobile_number' value='{{ $billingCard->mobile_number }}'>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer text-center">

                                        <div class="form-group pull-left">
                                            <a href='{{ route('billingHome') }}' class='btn btn-secondary'>Back</a>
                                        </div>

                                        <div class="form-group pull-right">
                                            <input type="submit" class='btn btn-primary'>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

@stop

resources/views/user_payment_config/index.blade.php
@extends('layouts.master')

@section('content')

@include('layouts.errors')
<style>
    div.col-md-4 {
        margin-bottom:20px;
    }
</style>
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <div class="lead">Billing Cards</div>
            </div>
            <div class="card-body">
                <div class="card-text">

                    <div class="row">

                        @if($billingCards->isEmpty() === FALSE)

                            @foreach($billingCards as $card)
                                <div class="col-md-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="card-text">
                                                <p class='text-center'><strong>Billing</strong></p>

                                                <p>{{ $card->card_holder_name }}</p>
                                                <p>{{ $card->card_number }}</p>
                                                <p>{{ $card->expiry_date }}</p>

                                                <p class='text-center'><strong>Address</strong></p>
                                                <p>{{ $card->building_name }}</p>
                                                <p>{{ $card->street_address1 }}</p>
                                                <p>{{ $card->street_address2 }}</p>
                                                <p>{{ $card->street_address3 }}</p>
                                                <p>{{ $card->street_address4 }}</p>
                                                <p>{{ $card->county }}</p>
                                                <p>{{ $card->city }}</p>
                                                <p>{{ $card->postcode }}</p>
                                                <p>{{ $card->country }}</p>
                                                <p>{{ $card->formatted_phone_number }}</p>
                                                <p>{{ $card->formatted_mobile_number }}</p>

                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <div class="pull-left">
                                                <a href='{{ route('billingDelete', $card->id) }}' class='btn btn-danger'>Delete</a>
                                            </div>

                                            <div class="pull-right">
                                                <a href='{{ route('billingEdit', $card->id) }}' class='btn btn-info'>Edit Card</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach

                        @else
                            <div class="col-md-12">
                                <p class='text-center'>You have no billing cards</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ route('billingCreate') }}" class="btn btn-primary float-right">Add Card</a>
            </div>
        </div>

    </div>

</div>

@stop